//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TUGraz.VectoCore.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TUGraz.VectoCore.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rims,F(a),F(b)
        ///5° DC Rims,3.03,3.03
        ///15° DC Rims,3.03,3.05
        ///Multipurpose – Radial,3,3
        ///Multipurpose – Diagonal,2.94,2.94
        ///.
        /// </summary>
        internal static string DeclarationRims {
            get {
                return ResourceManager.GetString("DeclarationRims", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wheel,Inertia,d,Size-Class(0/1)
        ///9 R 22.5,8.9,970,0
        ///9.00 R 20,10.5,1018,0
        ///9.5 R 17.5,4.9,842,0
        ///10 R 17.5,5,858,0
        ///10 R 22.5,11,1020,0
        ///10.00 R 20,13.1,1025,0
        ///11 R 22.5,14.4,1050,0
        ///11.00 R 20,14.6,1082,0
        ///12 R 22.5,16.8,1084,0
        ///12.00 R 20,19.5,1122,0
        ///12.00 R 24,27.7,1226,0
        ///12.5 R 20,12.7,1120,0
        ///13 R 22.5,20,1124,0
        ///14.00 R 20,30.8,1238,0
        ///14.5 R 20,14.8,1092,0
        ///16.00 R 20,47.5,1343,0
        ///215/75 R 17.5,3.9,767,0
        ///225/70 R 17.5,4,759.5,0
        ///225/75 R 17.5,4,782,0
        ///235/75 R 17.5,4.5,797,0
        ///245/70 R 17.5,5.2,7 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DeclarationWheels {
            get {
                return ResourceManager.GetString("DeclarationWheels", resourceCulture);
            }
        }
    }
}
